mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('recommendation/', include('recommendation.urls')),
    path('admin/', admin.site.urls),
]

recommendation/urls.py
from django.urls import path
from django.conf.urls import url

from . import views

app_name = 'recommendation'
urlpatterns = [
    path('', views.index, name='index'),
    url(r'^movie/search', views.movie, name='movie'),
]

recommendation/models.py
from django.db import models

# Create your models here.

recommendation/forms.py
from django import forms

class NameForm(forms.Form):
    your_name = forms.CharField(label='Your name', max_length=100)

recommendation/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.http import HttpResponse
from django.http import Http404
from django.views.decorators.csrf import csrf_exempt
import engine as eng
import urllib.request
import urllib.parse
import re
import json

def index(request):
    lom = eng.movielist
    return render(request, 'recommendation/index.html', {'lom':lom})
    
@csrf_exempt
def movie(request):
    if request.method == 'GET':
        movie_title = request.GET.get('movieChoice', False)
        lom = eng.movielist
        if movie_title in lom:
            index = eng.movielist.index(movie_title)
            overview = eng.infolist[index]
            director = eng.directors[index]
            genres = str(eng.genre[index]).replace("'","")[1:-1]
            companies = str(eng.companieslist[index]).replace("'","")[1:-1]
            runtime = str(int(eng.runtimelist[index]) // 60) + "h" + str(int(eng.runtimelist[index]) % 60) + "m"
            query_string = urllib.parse.urlencode({"search_query" : movie_title + "trailer"})
            html_content = urllib.request.urlopen("http://www.youtube.com/results?" + query_string)
            search_results = re.findall(r'href=\"\/watch\?v=(.{11})', html_content.read().decode())
            video = "http://www.youtube.com/embed/" + search_results[0] + "?autoplay=1"
        else:
            raise Http404("No data found for movie, please try something else.")
        return render(request, 'recommendation/movie.html', {'movie_title': movie_title, 'overview':overview, 'lom':lom, 'video':video, 'director':director, 'genres':genres, 'companies':companies, 'runtime':runtime})
    if request.method == 'POST':
        recommendation_choice = request.POST.get('recommendationChoice', False)
        movie_title = request.POST.get('movieChoice', False)
        
        recommendation_info = eng.return_recommendation(movie_title, recommendation_choice)
        recommendation_general_info = eng.return_general(movie_title)
        
        rec_titles = []
        rec_overviews = []
        genres = []
        directors = []
        companies = []
        videos = []
        for i in recommendation_info:
            query_string = urllib.parse.urlencode({"search_query" : i.get("title", "invalid choice") + "trailer"})
            html_content = urllib.request.urlopen("http://www.youtube.com/results?" + query_string)
            search_results = re.findall(r'href=\"\/watch\?v=(.{11})', html_content.read().decode())
            video = "http://www.youtube.com/embed/" + search_results[0]
            videos.append(video)
            rec_titles.append(i.get("title", "invalid choice"))
            rec_overviews.append(i.get("overview", "invalid choice"))
            genres.append(i.get("genres", "invalid choice"))
            directors.append(i.get("director", "invalid choice"))
            companies.append(i.get("companies", "invalid choice"))
            
        for i in recommendation_general_info:
            query_string = urllib.parse.urlencode({"search_query" : i.get("title", "invalid choice") + "trailer"})
            html_content = urllib.request.urlopen("http://www.youtube.com/results?" + query_string)
            search_results = re.findall(r'href=\"\/watch\?v=(.{11})', html_content.read().decode())
            video = "http://www.youtube.com/embed/" + search_results[0]
            videos.append(video)
            rec_titles.append(i.get("title", "invalid choice"))
            rec_overviews.append(i.get("overview", "invalid choice"))
            genres.append(i.get("genres", "invalid choice"))
            directors.append(i.get("director", "invalid choice"))
            companies.append(i.get("companies", "invalid choice"))
        
        response_data = {}

        response_data['choice'] = recommendation_choice
        response_data['titles'] = rec_titles
        response_data['overviews'] = rec_overviews
        response_data['genres'] = genres
        response_data['directors'] = directors
        response_data['companies'] = companies
        response_data['vid_links'] = videos
        
        return HttpResponse(json.dumps(response_data), content_type='application/json')

recommendation/templates/recommendation/index.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Recommendation Site</title>
    {% load static %}
      <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
      <link rel="stylesheet" type="text/css" href="{% static 'recommendation/css/style.css' %}">
  </head>
  <body>
    <div class="container mt-4">
      <div class="wrapper">
        <h1>Please select a movie.</h1>
        <div class="dropdown">
          <form action="{% url 'recommendation:movie' %}" method="get">
            {% csrf_token %}
            <ul class="dropMenu">
              <div class="row">
                <div class="col-10" style="padding-right: 0">
                  <input id="myInput" type="text" name="movieChoice" placeholder="Search...">
                </div>
                <div class="col-2" style="padding-left: 0">
                  <button class="btn btn-primary" id="searchSubmit" type="submit" name="button">SEARCH</button>
                </div>
              </div>
              {% for option in lom %}
                <li><button class="movieButton" type="button" onclick="search(this)">{{ option }}</button></li>
              {% endfor %}
            </ul>
          </form>
        </div>
      </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script>
    $(document).ready(function(){
      $("#myInput").on("keyup", function() {
        var value = $(this).val().toLowerCase();
        $(".dropMenu li").filter(function() {
          $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
        });
      });
    });
    function search(button){
      document.getElementById("myInput").value = button.innerHTML;
    }
    </script>
  </body>
</html>

recommendation/templates/recommendation/movie.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>{{ movie_title }}</title>
    {% load static %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'recommendation/css/style.css' %}">
  </head>
  <body>
    <div class="container mt-4">
      <div class="row">
        <div class="col-10">
          <h1 style="font-weight: bold;">{{ movie_title }}</h1>
        </div>
        <div class="col-2">
          <a class="returnLink" href="http://127.0.0.1:8000/recommendation/" type="button" name="button">Return to list</a>
        </div>
      </div>
      <div class="row">
        <div class="col-12 col-md-6">
          <iframe width="100%" height="400"
            src="{{ video }}">
          </iframe>
        </div>
        <div class="col-12 col-md-6">
          <div class="row">
            <div class="col-12">
              <h4 style="font-weight: bold;">Overview:</h4>
              <h5>{{ overview }}</h5>
              <h4 style="font-weight: bold;">Director:</h4>
              <h5>{{ director }}</h5>
              <h4 style="font-weight: bold;">Genres:</h4>
              <h5>{{ genres }}</h5>
              <h4 style="font-weight: bold;">Production Companies:</h4>
              <h5>{{ companies }}</h5>
              <h4 style="font-weight: bold;">Runtime:</h4>
              <h5>{{ runtime }}</h5>
            </div>
          </div>
        </div>
      </div>
      <div class="row justify-content-center mt-4">
        <div class="col-6">
          <form id="recForm" action="" method="post">
            <div class="form-group">
              <label for="recommendationChoice">Which part of this movie would you be interested in seeing more of?</label>
              <select class="form-control" id="recommendationChoice" name="recommendationChoice">
                <option selected disabled hidden style='display: none' value=''></option>
                <option value="director">The director</option>
                <option value="plot">The plot</option>
                <option value="genre">The genre</option>
                <option value="company">The studios</option>
              </select>
              <input type="hidden" id="movieChoice" name="movieChoice" value="{{ movie_title }}">
            </div>
            <div id="results"></div>
            <div class="form-submit">
              <button class="btn btn-primary" type="submit">Submit</button>
            </div>
          </form>
        </div>
      </div>
      <div class="row justify-content-center" style="margin-top: 50px;">
        <div class="col-2" style="position: relative;">
          <div id="loading"></div>
        </div>
      </div>
      <div class="row">
        <div class="col-12">
          <ul id="recommendList" style="list-style:none; display: none;"></ul>
          <ul id="recommendListGeneral" style="list-style:none; display: none;"></ul>
        </div>
      </div>
      <div class="row justify-content-center">
        <div class="col-2">
          <button id="swapButton" class="btn btn-primary mt-2 mb-2" type="button" style="display: none;">Swap Lists</button>
        </div>
      </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.4.1.js" integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script type="text/javascript">
      $('#recForm').on('submit', function(event){
        event.preventDefault();
        create_post();
      });
      $('#swapButton').click(function(){
        if($('#recommendList').css('display') === 'none') {
          $('#recommendList').show(0);
          $('#recommendListGeneral').hide(0);
        } else {
          $('#recommendList').hide(0);
          $('#recommendListGeneral').show(0);
        }
      })
      function create_post(){
          document.getElementById("loading").style.display = "block";
          var ulstr = ""
          var rstr = ""
          for (var i = 0; i < 10; i++) {
            ulstr += "<li id='rec" + i +"'>";
            ulstr += '<form action="{% url "recommendation:movie" %}" method="get">';
            ulstr += '<input id="input' + i + '" type="text" name="movieChoice" value="" hidden></input>';
            ulstr += '<button type="submit" name="button" class="rowButton">';
            ulstr += '<div class="row recRow">';
            ulstr += '<div class="col-12 recCol">';
            ulstr += '<div class="row"><div class="col-4 recVid">';
            ulstr += '<iframe id="recVid' + i + '" width="100%" height="210" src=""></iframe>';
            ulstr += '</div>';
            ulstr += '<div class="col-8 recText"><div class="row">';
            ulstr += '<div class="col-7"><h3 id="title' + i + '" style="font-weight: bold;"></h3></div>';
            ulstr += '<div class="col-5" style="position: relative"><h5 id="choicetext' + i + '" class="choiceText"></h5></div>';
            ulstr += '</div><p id="overviewtext'+i+'"></p>';
            ulstr += '<p style="font-weight: bold;" class="mt-2" id="companytext'+i+'" class="choiceText"></p>';
            ulstr += '</div></div></div></div></button></form></li>';
          }
          for (var i = 10; i < 20; i++) {
            rstr += "<li id='rec" + i +"'>";
            rstr += '<form action="{% url "recommendation:movie" %}" method="get">';
            rstr += '<input id="input' + i + '" type="text" name="movieChoice" value="" hidden></input>';
            rstr += '<button type="submit" name="button" class="rowButton">';
            rstr += '<div class="row recRow">';
            rstr += '<div class="col-12 recCol">';
            rstr += '<div class="row"><div class="col-4 recVid">';
            rstr += '<iframe id="recVid' + i + '" width="100%" height="210" src=""></iframe>';
            rstr += '</div>';
            rstr += '<div class="col-8 recText"><div class="row">';
            rstr += '<div class="col-7"><h3 id="title' + i + '" style="font-weight: bold;"></h3></div>';
            rstr += '<div class="col-5" style="position: relative"><h5 id="choicetext' + i + '" class="choiceText"></h5></div>';
            rstr += '</div><p id="overviewtext'+i+'"></p>';
            rstr += '<p style="font-weight: bold;" class="mt-2" id="companytext'+i+'" class="choiceText"></p>';
            rstr += '</div></div></div></div></button></form></li>';
          }
          document.getElementById("recommendList").innerHTML = ulstr;
          document.getElementById("recommendListGeneral").innerHTML = rstr;
          $.ajax({
            url : "",
            type : "POST",
            data : { recommendationChoice : $('#recommendationChoice').val(), movieChoice : $('#movieChoice').val() },

            success : function(json) {
              $('#recommendationChoice').val('');
              document.getElementById("loading").style.display = "none";
              document.getElementById("recommendList").style.display = "block";
              document.getElementById("swapButton").style.display = "block";
              //document.getElementById("recommendListGeneral").style.display = "block";
              for (var i = 0; i < json['titles'].length; i++) {
                document.getElementById("input" + i).value = JSON.stringify(json['titles'][i], undefined, 2).replace(/['"]+/g, '');
                document.getElementById("title" + i).innerHTML = JSON.stringify(json['titles'][i], undefined, 2).replace(/['"]+/g, '');
                document.getElementById("recVid" + i).src = JSON.stringify(json['vid_links'][i], undefined, 2).replace(/['"]+/g, '');
                document.getElementById("overviewtext" + i).innerHTML = JSON.stringify(json['overviews'][i], undefined, 2).replace(/['"]+/g, '');
                if (JSON.stringify(json['choice'], undefined, 2).replace(/['"]+/g, '') == "director") {
                  document.getElementById("choicetext" + i).innerHTML = JSON.stringify(json['directors'][i], undefined, 2).replace(/['"]+/g, '');
                } else if (JSON.stringify(json['choice'], undefined, 2).replace(/['"]+/g, '') == "company") {
                  document.getElementById("choicetext" + i).innerHTML = "";
                  document.getElementById("companytext" + i).innerHTML = JSON.stringify(json['companies'][i], undefined, 2).replace(/['"]+/g, '');
                } else {
                  document.getElementById("choicetext" + i).innerHTML = JSON.stringify(json['genres'][i], undefined, 2).replace(/['"]+/g, '');
                }
              }
              console.log(json);
            },

            error : function(xhr,errmsg,err) {
              $('#results').html("<div class='alert-box alert radius' data-alert>Oops! We have encountered an error.<a href='#' class='close'>&times;</a></div>");
              console.log(xhr.status + ": " + xhr.responseText);
            }
          });
      };
    </script>
  </body>
</html>